Repository OracleStation/OracleStation, pull requests merged in 2018-09, with the labels that each got.

#1194 Minebots no longer have genders
  code/modules/mining/minebot.dm
Labels: Fix

#1195 Added Ian things for the Blueshield armor and berets
  code/datums/dog_fashion.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/suits/armor.dm
  icons/mob/corgi_back.dmi
  icons/mob/corgi_head.dmi
Labels: Feature

#1182 Fixes erroneous pipe_state for heat exchange junctions.
  code/modules/atmospherics/machinery/pipes/heat_exchange/junction.dm
Labels: Fix

#1171 Infiltrator event!
  code/modules/admin/verbs/one_click_antag.dm
  code/modules/events/infiltrators.dm
  tgstation.dme
Labels: Feature

#1152 Get rid of portable chem dispensers, and make the normal chem dispensers constructable and upgradable
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
Labels: Feature, Tweak, Wiki Change

#1198 Fixes chem dispenser bug
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
Labels: Fix

#1205 Fixes Liquid Solder
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Fix

#1208 Readds additional chems upon upgrading chem dispensers
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
Labels: Tweak

#1196 Changes security softcap colors to be closer to the uniform's
  icons/mob/head.dmi
Labels: Fix
