Repository OracleStation/OracleStation, pull requests merged in 2018-04, with the labels that each got.

#792 Fixed liver enhancer so that it works properly
  code/datums/diseases/advance/presets.dm
Labels: Fix

#793 Turret Fix/Changes+Efficiency Tg ports
  code/__HELPERS/maths.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/ai.dm
  code/_onclick/click.dm
  code/_onclick/cyborg.dm
  code/_onclick/observer.dm
  code/_onclick/other_mobs.dm
  code/controllers/subsystem/processing/projectiles.dm
  code/datums/antagonists/datum_traitor.dm
  code/datums/mutations.dm
  code/datums/status_effects/debuffs.dm
  code/game/gamemodes/clock_cult/clock_helpers/slab_abilities.dm
  code/game/machinery/computer/law.dm
  code/game/machinery/computer/message.dm
  code/game/machinery/computer/robot.dm
  code/game/machinery/porta_turret/portable_turret.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/objects/structures/manned_turret.dm
  code/game/objects/structures/reflector.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mining/equipment/kinetic_crusher.dm
  code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/silicon/robot/laws.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_defense.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/bot/ed209bot.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/jungle_mobs.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_helpers.dm
  code/modules/power/singularity/emitter.dm
  code/modules/projectiles/firing.dm
  code/modules/projectiles/guns/beam_rifle.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/research/experimentor.dm
  code/modules/spells/spell.dm
  code/modules/spells/spell_types/aimed.dm
  icons/obj/structures.dmi
  tgstation.dme
Labels: Feature, Port, Tweak

#790 Fixed the emergency shuttle quick launch
  code/modules/shuttle/emergency.dm
Labels: Fix

#795 Fixes MetaStation reflector issues
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Fix

#788 Various OracleUI fixes.
  code/modules/oracle_ui/README.md
  code/modules/oracle_ui/hookup_procs.dm
  code/modules/oracle_ui/themed.dm
  html/oracle_ui/themes/nano/sui-nano-common.js
Labels: Fix

#796 Box and Delta reflector fix
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Fix

#805 Emitter projectile Fix
  code/game/objects/items/shields.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/simple_animal/constructs.dm
Labels: Fix

#803 Ammo sprite fixed
  icons/obj/ammo.dmi
Labels: Fix

#800 Fixed changling escape objectives
  code/game/gamemodes/objective.dm
Labels: Fix

#809 Changed changeling_scaling_coefficient from 6 to 8 to combat ridiculous changeling numbers on high pop
  config/game_options.txt
Labels: Tweak

#812 When there's something rude in your neighborhood
  code/game/gamemodes/miniantags/revenant/revenant_abilities.dm
Labels: Fix

#799 Removes cat ears from the AutoDrobe
  code/game/machinery/vending.dm
Labels: Controversial, Removal

#801 Changerdanger!!!
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/changeling/powers/tiny_prick.dm
  icons/mob/screen_gen.dmi
Labels: Feature

#808 Credit Tweaks
  code/_onclick/hud/credits.dm
  code/game/gamemodes/game_mode.dm
  icons/credits.dmi
  tools/CreditsTool/CreditsTool.csproj
  tools/CreditsTool/CreditsTool.exe
  tools/CreditsTool/Program.cs
  tools/CreditsTool/UpdateCreditsDMI.sh
  tools/CreditsTool/remappings.txt
Labels: Removal, Tweak

#747 ID Card Icon Changes
  icons/obj/card.dmi
Labels: Sprites

#818 Lint and Correct README.md for Oracle
  README.md
Labels: Tweak

#815 Giving new verbs for admins to clean atmos messes up.
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/randomverbs.dm
Labels: Admin Tools

#817 Dissolves Cargonia
  code/game/gamemodes/gang/gang.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/machinery/computer/card.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/cargo_service.dm
  code/modules/jobs/jobs.dm
  strings/sillytips.txt
Labels: Tweak

#828 BS Delta Door Fix
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Fix

#823 Ports a few code improvements
  code/__DEFINES/admin.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/say.dm
  code/__DEFINES/subsystems.dm
  code/_compile_options.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Port, Refactor/Code Improvement

#846 Splits mutations Into Subfolder
  code/datums/mutations.dm
  code/datums/mutations/body.dm
  code/datums/mutations/chameleon.dm
  code/datums/mutations/cold_resistance.dm
  code/datums/mutations/hulk.dm
  code/datums/mutations/sight.dm
  code/datums/mutations/speech.dm
  code/datums/mutations/telekinesis.dm
  tgstation.dme
Labels: Refactor/Code Improvement

#839 Cultist fixed
  code/game/machinery/cryopod.dm
Labels: Fix

#844 Fixed the AI (With no stupid additional commits)
  code/modules/mob/living/silicon/ai/death.dm
Labels: Fix

#829 Ports Floor Painter From Paradise
  code/game/objects/items/airlock_painter.dm
  code/game/objects/items/devices/floor_painter.dm
  code/game/objects/items/devices/pipe_painter.dm
  code/modules/research/designs/autolathe_designs.dm
  icons/obj/objects.dmi
  icons/turf/decals.dmi
  icons/turf/floors.dmi
  tgstation.dme
Labels: Port, Tweak

#847 Admin Announce Tweak
  code/modules/admin/admin.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  interface/stylesheet.dm
Labels: Tweak

#849 Ready Player None
  code/modules/mob/mob.dm
Labels: Fix

#856 Fixes rogue pixels on the ID cards
  icons/obj/card.dmi
Labels: Fix, Sprites

#857 Fixes the solar duplication
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Fix, MetaStation

#842 Chem Implant Action Button Removal
  code/game/objects/items/implants/implant.dm
  code/game/objects/items/implants/implant_chem.dm
Labels: Balance, Controversial
