Repository OracleStation/OracleStation, pull requests merged in 2018-08, with the labels that each got.

#1078 Expands IAA office in metastation
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: MetaStation

#1125 Fixes feature
  code/game/objects/buckling.dm
Labels: Fix

#1123 Updates Janitorcarts
  code/game/objects/structures/janicart.dm
  code/game/objects/structures/mop_bucket.dm
  icons/obj/janitor.dmi
Labels: Tweak

#1135 Dwarves will now be kicked out of mob holders whenever they grow
  code/datums/mutations/body.dm
Labels: Fix

#1116 Adds icon smoothing for plating.
  code/datums/components/archaeology.dm
  code/game/turfs/simulated/floor/plating.dm
  code/game/turfs/simulated/floor/plating/asteroid.dm
  code/game/turfs/simulated/floor/plating/misc_plating.dm
  icons/turf/floors.dmi
  icons/turf/floors/plating.dmi
Labels: Sprites

#1149 Monkeys no longer remove your hair when worn
  code/modules/mob/living/inhand_holder.dm
Labels: Fix

#1062 Removes the "die a glorious death" objective.
  code/datums/antagonists/datum_traitor.dm
Labels: Tweak

#1071 Mutation Toxin Rework
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/food_and_drinks/kitchen_machinery/processor.dm
  code/modules/mob/living/blood.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
Labels: Tweak, Wiki Change

#1096 Preserve supply console contraband/emag value
  code/modules/cargo/console.dm
Labels: Fix

#1110 Wallet icon_state fallback
  code/game/objects/items/storage/wallets.dm
Labels: Fix

#1114 Removes baseball bat recipe
  code/game/objects/items/stacks/sheets/sheet_types.dm
Labels: No Fun PR, Removal

#1118 more text filter stuff
  code/__HELPERS/text_filter.dm
  code/modules/mob/mob_helpers.dm
  strings/retard_regex.txt
Labels: Tweak

#1121 Constructable TEGs
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/atmospherics/machinery/components/binary_devices/circulator.dm
  code/modules/atmospherics/machinery/components/components_base.dm
  code/modules/atmospherics/machinery/datum_pipeline.dm
  code/modules/cargo/packs.dm
  code/modules/power/generator.dm
  code/modules/research/designs/machine_designs.dm
  icons/obj/atmospherics/components/binary_devices.dmi
  icons/obj/power.dmi
  icons/vg/obj/teg.dmi
Labels: Feature, Port, Sprites, Wiki Change

#1126 Lockboxes are harder to break
  code/game/objects/items/storage/lockbox.dm
Labels: Tweak

#1151 swarmers can't eat field generators
  code/game/gamemodes/miniantags/bot_swarm/swarmer.dm
Labels: Tweak

#1148 Round weighting now reduces the chances of repeating a recently played mode
  code/controllers/configuration/configuration.dm
  code/controllers/subsystem/persistence.dm
  config/game_options.txt
Labels: Config Change, Tweak

#1160 GPS Teleportation Console bug.
  code/game/objects/items/devices/gps.dm
Labels: Fix

#1155 Disease outbreaks now have a chance of generating a random advanced virus
  code/datums/diseases/advance/presets.dm
  code/modules/events/disease_outbreak.dm
Labels: Feature

#1153 Gives the Antimatter Engine some love
  code/modules/power/antimatter/containment_jar.dm
  code/modules/power/antimatter/control.dm
  icons/obj/machines/antimatter.dmi
  icons/vg/obj/antimatter.dmi
Labels: Feature, Licensing

#1138 Food cart changes
  icons/obj/kitchen.dmi
Labels: Sprites

#1173 Travis CI Fixes
  .travis.yml
  tools/travis/before_build_tools.sh
  tools/travis/build_tools.sh
  tools/travis/install_build_tools.sh
Labels: Backend, High Priority

#1176 Compile warning on < 512
  code/_compile_options.dm
Labels: Backend

#1174 Meson Fixes
  code/__HELPERS/game.dm
  code/modules/clothing/glasses/engine_goggles.dm
Labels: Fix, Port

#1113 Limit channels of independent radio transmissions
  code/game/machinery/telecomms/broadcasting.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/awaymissions/capture_the_flag.dm
Labels: Tweak
