Repository OracleStation/OracleStation, pull requests merged in 2018-06, with the labels that each got.

#936 Makes IAA jacket match the jumpsuit
  icons/mob/suit.dmi
Labels: Tweak

#941 Makes PDA crew manifest not require a cart
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/items/devices/PDA/virus_cart.dm
Labels: Tweak

#919 Vox can now wear ash drake armor
  code/modules/clothing/suits/cloaks.dm
  icons/mob/species/vox/head.dmi
  icons/mob/species/vox/suit.dmi
Labels: Sprites

#950 Don't eat the crayons
  code/datums/datumvars.dm
  code/game/objects/effects/decals/crayon.dm
Labels: Admin Tools, Tweak

#943 PDA Interface Redesign
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/cart.dm
  html/browser/common.css
  icons/pda_icons/pda_atmos.png
  icons/pda_icons/pda_back.png
  icons/pda_icons/pda_bell.png
  icons/pda_icons/pda_blank.png
  icons/pda_icons/pda_boom.png
  icons/pda_icons/pda_bucket.png
  icons/pda_icons/pda_chatroom.png
  icons/pda_icons/pda_cleanbot.png
  icons/pda_icons/pda_crate.png
  icons/pda_icons/pda_cuffs.png
  icons/pda_icons/pda_dronephone.png
  icons/pda_icons/pda_eject.png
  icons/pda_icons/pda_exit.png
  icons/pda_icons/pda_flashlight.png
  icons/pda_icons/pda_floorbot.png
  icons/pda_icons/pda_honk.png
  icons/pda_icons/pda_locked.PNG
  icons/pda_icons/pda_mail.png
  icons/pda_icons/pda_medbot.png
  icons/pda_icons/pda_medical.png
  icons/pda_icons/pda_menu.png
  icons/pda_icons/pda_mule.png
  icons/pda_icons/pda_notes.png
  icons/pda_icons/pda_power.png
  icons/pda_icons/pda_rdoor.png
  icons/pda_icons/pda_reagent.png
  icons/pda_icons/pda_refresh.png
  icons/pda_icons/pda_scanner.png
  icons/pda_icons/pda_signaler.png
  icons/pda_icons/pda_status.png
Labels: Feature

#952 PDA UI Oversight Fixes
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/PDA_types.dm
  code/game/objects/items/devices/PDA/cart.dm
Labels: Fix, Tweak

#963 Replaces request console sprites
  icons/obj/terminals.dmi
Labels: Tweak

#934 Changeling assassinate no longer gives you the person's real name.
  code/game/gamemodes/changeling/changeling.dm
Labels: Tweak

#970 Updated Wall shield generator sprites
  icons/obj/stationobjs.dmi
Labels: Tweak

#969 Alarming Alarm sprites and more sprites
  code/modules/atmospherics/machinery/airalarm.dm
  icons/obj/monitors.dmi
  icons/obj/status_display.dmi
Labels: Tweak

#979 Removes QM Access from irrelevant jobs
  code/modules/jobs/job_types/cargo_service.dm
Labels: Tweak

#980 Updates PDA painter sprites
  icons/obj/pda.dmi
Labels: Feature

#981 Added a cool-down for Resting
  code/modules/mob/living/living.dm
  code/modules/mob/mob_defines.dm
Labels: Balance, Tweak

#982 heck
  code/modules/mob/living/carbon/alien/alien.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/living.dm
Labels: Fix

#983 Quick Fix! Makes it so you can only spawn atmos machinery with pipe dispensers.
  code/game/machinery/pipe/pipe_dispenser.dm
Labels: Exploit, Fix, High Priority

#988 Fixes: Some orbital stack overflows
  code/modules/mob/transform_procs.dm
  code/modules/orbit/orbit.dm
  code/modules/projectiles/projectile/magic.dm
Labels: Fix, High Priority

#989 Fixes a crash vector
  code/modules/research/experimentor.dm
Labels: Fix, High Priority

#986 Medibot sprite update
  icons/mob/aibots.dmi
Labels: Sprites

#992 Bad href exploit, bad! *whacks with newspaper*
  code/modules/client/preferences.dm
Labels: Fix

#990 Removes cat ears, purrbation, and the anime button
  _maps/RandomRuins/SpaceRuins/spacehotel.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  code/datums/datumvars.dm
  code/datums/dog_fashion.dm
  code/game/gamemodes/wizard/artefact.dm
  code/game/objects/effects/spawners/bundle.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/implants/implantchair.dm
  code/modules/admin/secrets.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/crafting/recipes.dm
  code/modules/events/wizard/curseditems.dm
  code/modules/mining/abandoned_crates.dm
  code/modules/mob/living/carbon/human/human.dm
  icons/mob/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Controversial, Removal

#946 Bible Sounds Revisited
  code/game/objects/items/storage/book.dm
Labels: Tweak

#930 Removes the build your own shuttle kit
  config/unbuyableshuttles.txt
Labels: Config Change, Removal

#954 Crusher Changes
  code/modules/mining/equipment/kinetic_crusher.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/mining_mobs.dm
Labels: Tweak

#998 give them the clamps
  code/__DEFINES/math.dm
  code/game/machinery/autolathe.dm
Labels: Exploit, Fix, High Priority

#961 Cult Flavoured Updates and Deconvert Announcements
  code/game/gamemodes/cult/runes.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Feature

#996 Death to Cat Ears, part Two
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: Fix

#995 Ports TG's new mapmerge and dmi conflict fixer
  .gitattributes
  tools/hooks/README.md
  tools/hooks/dmi.merge
  tools/hooks/install.bat
  tools/hooks/install.sh
  tools/hooks/pre-commit.hook
  tools/hooks/python.sh
  tools/mapmerge/Convert Maps to TGM.bat
  tools/mapmerge/README.md
  tools/mapmerge/Run Map Conflict Fixer.bat
  tools/mapmerge/Run Map Merge - DMM.bat
  tools/mapmerge/Run Map Merge - TGM.bat
  tools/mapmerge/dmm2tgm.py
  tools/mapmerge/maintloot.py
  tools/mapmerge/map_conflict_fixer.py
  tools/mapmerge/map_helpers.py
  tools/mapmerge/mapmerger.py
  tools/mapmerge/path_update.py
  tools/mapmerge2/Prepare Maps.bat
  tools/mapmerge2/README.md
  tools/mapmerge2/convert.py
  tools/mapmerge2/dmi.py
  tools/mapmerge2/dmm.py
  tools/mapmerge2/dmm2tgm.bat
  tools/mapmerge2/frontend.py
  tools/mapmerge2/mapmerge.bat
  tools/mapmerge2/mapmerge.py
  tools/mapmerge2/merge_driver_dmi.py
  tools/mapmerge2/precommit.py
  tools/mapmerge2/requirements-install.bat
  tools/mapmerge2/requirements.txt
  tools/mapmerge2/tgm2dmm.bat
Labels: Developer Tools, Port

#966 Starts logging round ID in created notes.
  SQL/database_changelog.txt
  SQL/tgstation_schema.sql
  SQL/tgstation_schema_prefixed.sql
  code/modules/admin/sql_message_system.dm
Labels: Feature, SQL Change

#977 Intercom sprite update
  icons/obj/radio.dmi
  icons/obj/wallframe.dmi
Labels: Feature

#997 Fixes issues with stack crafting
  code/game/gamemodes/miniantags/bot_swarm/swarmer.dm
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/constructable_frame.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/washing_machine.dm
  code/game/mecha/equipment/tools/other_tools.dm
  code/game/mecha/equipment/tools/work_tools.dm
  code/game/mecha/mecha_construction_paths.dm
  code/game/objects/items/apc_frame.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/game/objects/items/stacks/sheets/light.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/structures/ai_core.dm
  code/game/objects/structures/crates_lockers/closets/syndicate.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/hydroponics/biogenerator.dm
  code/modules/hydroponics/grown/grass_carpet.dm
  code/modules/mining/machine_redemption.dm
  code/modules/mining/machine_stacking.dm
  code/modules/mining/ores_coins.dm
  code/modules/mob/living/simple_animal/bot/floorbot.dm
  code/modules/power/port_gen.dm
  code/modules/power/solar.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Fix, Port

#947 Genetics and Science Cut
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/modules/jobs/job_types/medical.dm
  code/modules/jobs/job_types/science.dm
Labels: Tweak, Wiki Change

#951 CMO labcoat buff
  icons/mob/species/vox/suit.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Tweak

#953 New Gas Sprites
  .travis.yml
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
  icons/effects/fire.dmi
  icons/effects/tile_effects.dmi
Labels: BYOND 512, Do Not Merge, Feature

#978 METASTATION - Cafeteria addition
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: MetaStation, Tweak

#1007 Mutation toxin minimum amounts.
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: No Fun PR, Tweak
