Repository OracleStation/OracleStation, pull requests merged in 2018-05, with the labels that each got.

#873 Ports species flags for viruses
  code/__DEFINES/DNA.dm
  code/datums/diseases/_MobProcs.dm
  code/datums/diseases/_disease.dm
  code/datums/diseases/advance/symptoms/species.dm
  code/datums/diseases/beesease.dm
  code/datums/diseases/magnitis.dm
  code/datums/diseases/parrotpossession.dm
  code/datums/diseases/rhumba_beat.dm
  code/datums/diseases/transformation.dm
  code/modules/mob/living/carbon/human/species_types/abductors.dm
  code/modules/mob/living/carbon/human/species_types/angel.dm
  code/modules/mob/living/carbon/human/species_types/corporate.dm
  code/modules/mob/living/carbon/human/species_types/ethari.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/carbon/human/species_types/ipc.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  code/modules/mob/living/carbon/human/species_types/synths.dm
  code/modules/mob/living/carbon/human/species_types/vox.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/mob/living/carbon/life.dm
Labels: Feature, Port

#874 Fixes maintainers
  tgstation.dme
Labels: Fix

#875 LOOC tweak
  code/modules/client/verbs/ooc.dm
Labels: Tweak

#752 Adds IPC Drinks
  code/game/machinery/vending.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
  icons/obj/drinks.dmi
  icons/obj/janitor.dmi
Labels: Feature, Port

#881 Whoops
  code/modules/client/verbs/ooc.dm
Labels: Fix

#893 Synthanol can now be created
  code/modules/reagents/chemistry/recipes/others.dm
Labels: Fix

#889 hotfix for chem recipes requiring fungus until a way to get fungus is added
  code/modules/reagents/chemistry/recipes/drugs.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/chemistry/recipes/toxins.dm
Labels: Tweak

#900 fixes dumb virology bug
  code/datums/diseases/advance/advance.dm
Labels: Fix

#905 Gas react is much more efficient
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
Labels: Performance, Port

#904 Removes unecessary compares in turf atmos init
  code/game/turfs/open.dm
Labels: Port, Refactor/Code Improvement

#898 Adds a mentor panel*
  code/modules/admin/admin_verbs.dm
  code/modules/admin/permissionverbs/permissionedit.dm
  code/modules/admin/topic.dm
  code/modules/mentor/mentor_ranks.dm
Labels: Admin Tools

#909 Mob spawners menu UI icon for ghosts
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/ghost.dm
  icons/mob/screen_ghost.dmi
Labels: Tweak

#910 Fixes ghost UI
  code/_onclick/hud/_defines.dm
Labels: Fix

#914 Fixes the mentor panel
  code/modules/admin/permissionverbs/permissionedit.dm
  code/modules/admin/topic.dm
  code/modules/mentor/mentor_ranks.dm
Labels: Admin Tools, Fix

#915 New Necropolis Tendril Loot
  code/modules/mining/lavaland/necropolis_chests.dm
Labels: Tweak

#932 Adds some perm checks
  code/modules/admin/admin_investigate.dm
  code/modules/admin/topic.dm
Labels: Admin Tools
