Repository OracleStation/OracleStation, pull requests merged in 2018-02, with the labels that each got.

#586 Genetics stuff works again.
  code/__DEFINES/DNA.dm
  code/datums/dna.dm
  code/datums/mutations.dm
  code/game/gamemodes/miniantags/abduction/gland.dm
  code/game/machinery/cloning.dm
  code/game/machinery/computer/cloning.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/hydroponics/grown/replicapod.dm
  code/modules/spells/spell_types/lichdom.dm
Labels: Fix

#585 more accurate timer on species locks
  code/modules/client/preferences.dm
  code/modules/jobs/job_exp.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Tweak

#600 Status panel shows playercount
  code/modules/mob/mob.dm
Labels: Tweak

#552 Lets IPCs drink.
  code/modules/mob/living/carbon/carbon.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/glass.dm
Labels: Tweak

#581 Prevents server crashing via mob spam
  code/__DEFINES/mobs.dm
  code/_globalvars/misc.dm
  code/controllers/configuration/entries/game_options.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/slime/death.dm
  code/modules/mob/living/simple_animal/slime/powers.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  config/game_options.txt
Labels: Backend, Balance, Config Change, Feature™

#583 Broken legs and crawling make you wayyy slower.
  code/modules/mob/living/carbon/carbon_movement.dm
Labels: Tweak

#582 Cargonian Independence (QM is a Head)
  code/game/gamemodes/gang/gang.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/machinery/computer/card.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/cargo_service.dm
  code/modules/jobs/jobs.dm
Labels: Tweak

#597 Makes IPC revival more spectacular
  code/modules/mob/living/carbon/human/damage_procs.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/ipc.dm
  code/modules/mob/living/living.dm
Labels: Feature

#604 Fixed supermatter monitor not detecting supermatters.
  code/modules/modular_computers/file_system/programs/sm_monitor.dm
  code/modules/power/supermatter/supermatter.dm
Labels: Fix

#615 ziptie fixes
  icons/obj/items_and_weapons.dmi
Labels: Fix

#613 Reduces burn damage reduction of bodypart_robotic by 1
  code/modules/mob/living/carbon/human/species_types/ipc.dm
  code/modules/surgery/bodyparts/bodyparts.dm
Labels: Tweak

#602 Wizardz objectives
  code/game/gamemodes/objective.dm
  code/game/gamemodes/wizard/wizard.dm
Labels: Tweak

#624 Blocks BYOND users from connecting...
  code/modules/client/client_procs.dm
Labels: Backend

#598 Buffs cursed heart
  code/game/gamemodes/wizard/artefact.dm
  code/modules/surgery/organs/heart.dm
Labels: Balance

#575 Mentors
  SQL/tgstation_schema.sql
  SQL/tgstation_schema_prefixed.sql
  code/__DEFINES/admin.dm
  code/__HELPERS/_logging.dm
  code/_globalvars/lists/mobs.dm
  code/_globalvars/logging.dm
  code/controllers/configuration/entries/config.dm
  code/game/world.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_ranks.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/holder2.dm
  code/modules/admin/secrets.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/client/client_procs.dm
  code/modules/client/verbs/ooc.dm
  code/modules/client/verbs/who.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/mentor/follow.dm
  code/modules/mentor/holder2.dm
  code/modules/mentor/mentor_ranks.dm
  code/modules/mentor/verbs/mentor_memo.dm
  code/modules/mentor/verbs/mentorhelp.dm
  code/modules/mentor/verbs/mentorpm.dm
  code/modules/mentor/verbs/mentorsay.dm
  config/config.txt
  config/mentors.txt
  interface/stylesheet.dm
  tgstation.dme
Labels: Feature, High Priority

#553 Internal Affairs Agents
  _maps/RandomRuins/SpaceRuins/crashedship.dmm
  _maps/RandomZLevels/moonoutpost19.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/access.dm
  code/__DEFINES/jobs.dm
  code/datums/antagonists/devil.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/clock_cult/clock_cult.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/devil/devil_game_mode.dm
  code/game/gamemodes/gang/gang.dm
  code/game/gamemodes/gang/gang_datum.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/machinery/computer/card.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/devices/PDA/PDA_types.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/briefcase.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/under/accessories.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/civilian.dm
  code/modules/jobs/jobs.dm
  code/modules/paperwork/faxmachine.dm
  code/modules/paperwork/stamps.dm
  config/jobs.txt
  icons/mob/hud.dmi
Labels: Feature

#618 CAS fix
  code/modules/games/cas.dm
Labels: Fix

#625 Picks Security Officers ahead of regular crew.
  code/controllers/subsystem/job.dm
Labels: Tweak

#631 Unifies mentorhelp colors to all be blue/pink
  code/modules/mentor/verbs/mentorpm.dm
Labels: High Priority, Tweak

#632 Replaces the default SS13 logo with the Oracle eye logo
  icons/oracle_eye.png
  interface/skin.dmf
Labels: Tweak

#637 Minor grammar fixes; change reconnect message size
  code/game/world.dm
Labels: Tweak

#630 Fixes IAA sunglasses and sechud icon
  code/modules/jobs/job_types/civilian.dm
  icons/mob/hud.dmi
Labels: Tweak

#629 Makes mentors show in Adminwho instead of Who
  code/modules/client/verbs/who.dm
Labels: Tweak

#644 Fixes a Tip of the Round
  strings/sillytips.txt
Labels: Fix

#641 Makes the credits show our contributors instead of just TG
  tools/CreditsTool/UpdateCreditsDMI.sh
  tools/CreditsTool/remappings.txt
Labels: Tweak

#646 Fixes offhand runtime del loop
  code/game/objects/items/twohanded.dm
Labels: Fix

#645 Fixes Spark_spread runtime
  code/game/objects/effects/effect_system/effect_system.dm
  code/game/objects/effects/effect_system/effects_sparks.dm
Labels: Fix

#647 Adminwho will no longer list admins as both admins and mentors
  code/modules/client/verbs/who.dm
Labels: Fix

#649 Fixes and stuff
  code/modules/client/client_procs.dm
Labels: Backend, Exploit, Fix

#650 "code" "review"
  code/modules/client/verbs/who.dm
Labels: Fix

#652 No more IPC clings. Probably. Hopefully.
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/changeling/traitor_chan.dm
  code/game/gamemodes/game_mode.dm
Labels: Fix

#656 Makes mentor OOC color less of an eyesore
  code/modules/client/verbs/ooc.dm
Labels: Tweak

#658 Makes mentor OOC color readable + Changes bikehorn to announcement sound
  code/modules/client/verbs/ooc.dm
  code/modules/mentor/verbs/mentorpm.dm
Labels: Tweak

#659 FIXES MY RETARDATION
  code/modules/mentor/verbs/mentorhelp.dm
Labels: Tweak

#636 Blood Pack Fix N° 3: The Bloodpackening
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/shuttles/emergency_cere.dmm
  _maps/shuttles/whiteship_meta.dmm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/cargo/packs.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
Labels: Fix

#606 [READY]Very minor Ashwalker buffs
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
Labels: Tweak

#633 Shameless drone buffs
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/living/simple_animal/friendly/drone/drones_as_items.dm
Labels: Controversial, Tweak, Unironic Drone Buff

#663 More IPC fixes
  code/__DEFINES/DNA.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/brain/posibrain.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/ipc.dm
  code/modules/surgery/organ_manipulation.dm
  code/modules/surgery/organs/liver.dm
Labels: Fix

#666 Replica pods work again
  code/modules/hydroponics/grown/replicapod.dm
Labels: Fix
