Repository OracleStation/OracleStation, pull requests merged in 2018-07, with the labels that each got.

#1021 mutation????
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Fix

#1016 Fixes and Minor Edit to Metastation
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: MetaStation

#1023 Performance tweaks + bug fix for some 511 clients
  code/_onclick/telekinesis.dm
  code/controllers/configuration/entries/config.dm
  code/modules/atmospherics/environmental/LINDA_turf_tile.dm
  code/modules/client/client_procs.dm
  code/modules/food_and_drinks/drinks/drinks.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
  code/modules/food_and_drinks/food/customizables.dm
  code/modules/food_and_drinks/food/snacks.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/food/snacks_pie.dm
  code/modules/food_and_drinks/food/snacks_salad.dm
  code/modules/food_and_drinks/food/snacks_soup.dm
  code/modules/food_and_drinks/pizzabox.dm
  code/modules/games/cards.dm
  code/modules/holiday/easter.dm
  code/modules/holodeck/items.dm
  code/modules/hydroponics/beekeeping/beebox.dm
  code/modules/hydroponics/beekeeping/honeycomb.dm
  code/modules/hydroponics/gene_modder.dm
  code/modules/hydroponics/grown/random.dm
  code/modules/hydroponics/sample.dm
  code/modules/hydroponics/seeds.dm
  code/modules/library/lib_items.dm
  code/modules/mining/abandoned_crates.dm
  code/modules/mining/equipment/explorer_gear.dm
  code/modules/mining/lavaland/ash_flora.dm
  code/modules/mining/machine_vending.dm
  code/modules/mining/mine_items.dm
  code/modules/mining/money_bag.dm
  code/modules/mob/living/carbon/alien/organs.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/mob/living/simple_animal/bot/construction.dm
  code/modules/mob/living/simple_animal/friendly/drone/drones_as_items.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/gutlunch.dm
  code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
  code/modules/modular_computers/computers/item/laptop_presets.dm
  code/modules/modular_computers/computers/item/tablet_presets.dm
  code/modules/modular_computers/hardware/hard_drive.dm
  code/modules/ninja/suit/suit.dm
  code/modules/paperwork/filingcabinet.dm
  code/modules/paperwork/paper_cutter.dm
  code/modules/paperwork/pen.dm
  code/modules/power/cell.dm
  code/modules/power/lighting.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/ammunition/ammo_casings.dm
  code/modules/projectiles/box_magazine.dm
  code/modules/projectiles/boxes_magazines/internal_mag.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/vehicles/speedbike.dm
  config/config.txt
Labels: BYOND 512, Performance

#1025 Wirecutters and screwdrivers
  code/game/objects/items/tools.dm
  icons/obj/tools.dmi
Labels: Fix

#920 [Ready] Digi Leg Sprites for all Uniforms
  code/game/objects/items.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/shorts.dm
  code/modules/mob/living/carbon/human/species.dm
  icons/mob/uniform.dmi
Labels: Feature

#960 METASTATION - Removes chaplain soul shard
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Removal

#1017 Bluespace Prophecy Fix
  icons/effects/effects.dmi
Labels: Fix

#1002 Crisper Fonts For Status Displays & Brig Timers
  code/game/machinery/doors/brigdoors.dm
  code/game/machinery/status_display.dm
Labels: Tweak

#1029 Blacklists another build
  .travis.yml
  code/modules/client/client_procs.dm
Labels: BYOND 512

#1030 Fixed the PANDEMIC vaccines.
  code/modules/reagents/chemistry/machinery/pandemic.dm
Labels: Fix

#1032 Fix various syntactic problems
  code/__HELPERS/_lists.dm
  code/__HELPERS/icons.dm
  code/modules/power/singularity/collector.dm
Labels: Refactor/Code Improvement

#1034 Fixes a Ziiroversight
  icons/mob/uniform.dmi
Labels: Fix

#1040 Sec jacket
  code/game/machinery/vending.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/species/vox/suit.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature

#1041 Corporate Uniform
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/modules/clothing/head/soft_caps.dm
  code/modules/clothing/under/jobs/security.dm
  icons/mob/head.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Fix

#1048 Minor bug fixes
  code/datums/mind.dm
  code/game/gamemodes/changeling/powers/transform.dm
  code/modules/surgery/bodyparts/bodyparts.dm
Labels: Fix

#1046 Fix the top menus in the skin not working
  code/datums/verbs.dm
  code/modules/client/client_procs.dm
Labels: Fix, High Priority, Port

#1038 Fobbing off AHelps to MHelps
  code/modules/admin/verbs/adminhelp.dm
  code/modules/mentor/verbs/mentorhelp.dm
Labels: Admin Tools

#1056 Lizuuurd
  icons/mob/uniform.dmi
Labels: Fix

#1060 Gives some Clown, Mime, Curator and Chaplain Service Headsets
  code/modules/jobs/job_types/civilian.dm
  code/modules/jobs/job_types/civilian_chaplain.dm
Labels: Tweak

#1001 Abductor Clothes
  code/game/gamemodes/miniantags/abduction/abduction_gear.dm
  code/game/gamemodes/miniantags/abduction/abduction_outfits.dm
  icons/mob/uniform.dmi
  icons/obj/abductor.dmi
Labels: Conflicts, Sprites

#1061 No More Revenant SSD Soul Absorbtion
  code/game/gamemodes/miniantags/revenant/revenant_abilities.dm
Labels: Tweak

#1050 Resprites blood cult structures
  icons/obj/cult.dmi
Labels: Feature, Sprites

#1065 Updates the dark yellowtiles
  icons/turf/floors.dmi
Labels: Tweak

#1069 Changes the gift box sprites pespective
  icons/obj/storage.dmi
Labels: Tweak

#1067 Updates the blood cult forge and pylon
  icons/obj/cult.dmi
Labels: Tweak

#1047 ID Card Ground Icons
  code/game/objects/items.dm
  code/game/objects/items/cards_ids.dm
  code/modules/clothing/outfits/standard.dm
  icons/obj/card.dmi
  icons/obj/card_ground.dmi
Labels: Feature

#1077 Briefcase fix and update
  code/game/objects/items/storage/briefcase.dm
  code/game/objects/structures/inflatable.dm
  code/modules/jobs/job_types/civilian.dm
Labels: Fix, Tweak

#1070 Effect fixing megathread 😂😂😂
  code/game/objects/effects/effect_system/effects_smoke.dm
Labels: Fix

#1086 Changes the snappop shuttle's chasm room with a brig.
  _maps/shuttles/emergency_clown.dmm
Labels: Misc Mapping, No Fun PR

#1088 whoops
  code/game/machinery/cryopod.dm
Labels: Fix

#1084 Adds ID painting to the PDA painter
  code/game/machinery/PDApainter.dm
  code/game/machinery/aug_manipulator.dm
  icons/obj/pda.dmi
  icons/obj/robotics.dmi
Labels: Feature

#1092 Remove gas_transfer_coefficient
  code/game/objects/items.dm
  code/modules/clothing/chameleon.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/masks/breath.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/utility.dm
  code/modules/clothing/suits/wiz_robe.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/research/xenobiology/xenobiology.dm
Labels: Refactor/Code Improvement

#1094 Library Book Fix
  code/modules/library/lib_machines.dm
Labels: Fix

#1075 Makes the med cyborg module candy dispenser less spammy
  code/game/objects/items/robot/robot_items.dm
Labels: Tweak

#1100 wiki link
  code/controllers/subsystem/job.dm
Labels: Fix

#824 Adds Ambient Occlusion (REQUIRES 512, WILL TRIP THE 512 REQUIRED FLAG)
  code/__DEFINES/layers.dm
  code/__DEFINES/misc.dm
  code/_onclick/hud/plane_master.dm
  code/game/area/areas.dm
  code/game/machinery/ai_slipper.dm
  code/game/machinery/hologram.dm
  code/game/machinery/igniter.dm
  code/game/objects/effects/decals/decal.dm
  code/game/objects/structures/lattice.dm
  code/game/turfs/open.dm
  code/modules/atmospherics/machinery/components/components_base.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: BYOND 512, Feature

#1031 Text filtering
  code/__HELPERS/text_filter.dm
  code/_globalvars/lists/names.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob_helpers.dm
  strings/retard_lines.txt
  tgstation.dme
Labels: Feature, Feature™, No Fun PR

#1057 HoP and Cap get those cute mini eguns instead of the big-ass ones
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Tweak

#1064 Adds a cryostorage room to Pubbystation
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Pubbystation

#1076 New Cloner Sprites
  code/game/machinery/cloning.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/mob/living/carbon/human/human.dm
  icons/obj/cloning.dmi
  icons/obj/cryo_mobs.dmi
  icons/obj/cryogenics.dmi
Labels: Sprites, Tweak

#1103 removes growth serum from amanita mushrooms
  code/modules/hydroponics/grown/mushrooms.dm
Labels: No Fun PR, Removal

#1108 Kills skateboard and scooter recipes
  code/game/objects/items/stacks/rods.dm
  code/modules/crafting/recipes.dm
Labels: No Fun PR, Removal

#1102 Tweaks to job playtime reqs
  code/modules/jobs/job_types/blueshield.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/cargo_service.dm
  code/modules/jobs/job_types/engineering.dm
  code/modules/jobs/job_types/medical.dm
  code/modules/jobs/job_types/science.dm
  code/modules/jobs/job_types/security.dm
  code/modules/jobs/job_types/silicon.dm
Labels: Tweak

#1101 Allow the light replacer to recycle objects directly off the floor
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/power/lighting.dm
Labels: Tweak

#1104 Adds descriptions for virus cartridges.
  code/game/objects/items/devices/PDA/virus_cart.dm
Labels: Tweak

#1095 Adds Standard Operating Procedure Books to the code
  code/game/objects/items/manuals.dm
  icons/obj/library.dmi
Labels: Feature

#1072 General animation fancification
  code/game/atoms_movable.dm
  code/game/objects/items.dm
  code/game/objects/items/storage/bags.dm
  code/modules/mob/inventory.dm
Labels: Tweak

#1111 Paramedic bling
  code/game/objects/items/storage/backpack.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/jobs/job_types/medical.dm
  icons/mob/back.dmi
  icons/mob/head.dmi
  icons/mob/species/vox/helmet.dmi
  icons/mob/species/vox/suit.dmi
  icons/mob/species/vox/uniform.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/storage.dmi
Labels: Feature, Fix, Sprites, Tweak

#1115 Conveyor update
  _maps/RandomRuins/SpaceRuins/deepstorage.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/cargo_birdboat.dmm
  _maps/shuttles/cargo_box.dmm
  _maps/shuttles/ferry_lighthouse.dmm
  code/modules/recycling/conveyor2.dm
  icons/obj/recycling.dmi
Labels: Feature

#994 Adds the ability to construct and deconstruct locker locks
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/bodybag.dm
  code/game/objects/structures/crates_lockers/closets/cardboardbox.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/genpop.dm
  code/game/objects/structures/crates_lockers/closets/secure/personal.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  goon/icons/obj/closet.dmi
Labels: Feature
