Repository OracleStation/OracleStation, pull requests merged in 2018-03, with the labels that each got.

#669 Makes SSD print more obvious.
  code/modules/mob/living/carbon/human/examine.dm
Labels: Tweak

#622 Drone hatches
  code/__DEFINES/flags.dm
  code/__DEFINES/layers.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_types.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  icons/obj/doors/hatches.dmi
  sound/machines/hatch_close.ogg
  sound/machines/hatch_open.ogg
Labels: Feature

#662 Adds plastitanium wall smoothing and plastitantium windows
  code/game/area/areas/shuttles.dm
  code/game/objects/structures/false_walls.dm
  code/game/objects/structures/window.dm
  code/game/turfs/simulated/wall/mineral_walls.dm
  icons/obj/smooth_structures/plastitanium_window.dmi
  icons/turf/walls/plastitanium_wall.dmi
Labels: Feature, Port

#672 Revert "Drone hatches"
  code/__DEFINES/flags.dm
  code/__DEFINES/layers.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_types.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  icons/obj/doors/hatches.dmi
  sound/machines/hatch_close.ogg
  sound/machines/hatch_open.ogg
Labels: Revert

#657 Revamps MetaStation Telecomms
  _maps/map_files/MetaStation/MetaStation.dmm
  code/game/objects/structures/signs.dm
  code/modules/paperwork/paper.dm
  icons/obj/decals.dmi
Labels: Tweak, Usability

#676 Suicide is painless
  code/modules/client/verbs/suicide.dm
  tgstation.dme
Labels: Fix, Oversight

#675 Fixes cryoing on cult rounds, hopefully.
  code/game/machinery/cryopod.dm
Labels: Fix

#673 Drone hatches II: The Hatchinator
  code/__DEFINES/flags.dm
  code/__DEFINES/layers.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_types.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  icons/obj/doors/hatches.dmi
  sound/machines/hatch_close.ogg
  sound/machines/hatch_open.ogg
Labels: Feature, Port

#678 Fixes RCD airlock drone hatches
  code/game/turfs/simulated/floor.dm
Labels: Fix

#681 Ports RIS/tg New Parallax
  code/_onclick/hud/parallax.dm
  icons/effects/parallax.dmi
Labels: Sprites, Tweak

#682 Fixes some visual bugs with drone hatches
  code/game/machinery/doors/airlock.dm
Labels: Fix

#668 Emagging a shuttle now violently throws people without seatbelts on ignition, and has a chance to break seatbelts.
  code/modules/shuttle/emergency.dm
  code/modules/shuttle/on_move.dm
  code/modules/shuttle/shuttle.dm
Labels: Feature, Port

#687 Adjusts Charter timers to be less awful
  code/game/objects/items/charter.dm
Labels: Tweak

#680 Makes it so Admin frozen players can't be moved
  code/modules/admin/verbs/randomverbs.dm
Labels: Admin Tools, Tweak

#684 Refactor get_players_for_role
  code/game/gamemodes/game_mode.dm
Labels: Playtest Before Merge, Refactor/Code Improvement

#699 whoops
  code/modules/mob/living/carbon/human/species.dm
Labels: Tweak

#691 Makes charter admin alert fucking huge
  code/game/objects/items/charter.dm
Labels: Tweak

#695 Medical Hud Upgrade
  code/game/data_huds.dm
  icons/mob/hud.dmi
Labels: Feature

#697 Clown Fixes. Honk!
  code/datums/antagonists/datum_traitor.dm
  code/datums/mutations.dm
  code/modules/jobs/job_types/civilian.dm
Labels: Tweak

#690 Sleeper Agent/Double Agent Tweaks
  code/datums/antagonists/datum_sleeper_agent.dm
  code/game/gamemodes/traitor/double_agents.dm
Labels: Tweak

#665 Emergency lights
  code/game/gamemodes/malfunction/Malf_Modules.dm
  code/modules/power/apc.dm
  code/modules/power/cell.dm
  code/modules/power/lighting.dm
  code/modules/research/designs/autolathe_designs.dm
  icons/mob/actions/actions_AI.dmi
  icons/obj/lighting.dmi
  tgui/assets/tgui.js
  tgui/src/interfaces/apc.ract
Labels: Feature, Playtest Before Merge, Port

#626 Crew Objectives
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/ticker.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/objects/items/devices/PDA/PDA_types.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/crew_objectives/_crew_objectives.dm
  code/modules/crew_objectives/cargo_objectives.dm
  code/modules/crew_objectives/civilian_objectives.dm
  code/modules/crew_objectives/command_objectives.dm
  code/modules/crew_objectives/engineering_objectives.dm
  code/modules/crew_objectives/medical_objectives.dm
  code/modules/crew_objectives/science_objectives.dm
  code/modules/crew_objectives/security_objectives.dm
  config/game_options.txt
  tgstation.dme
Labels: Feature, Port

#689 Minor vox fixing #1
  code/__DEFINES/DNA.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/machinery/computer/cloning.dm
  code/game/machinery/computer/dna_console.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/spacesuits/flightsuit.dm
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/suits/wiz_robe.dm
  code/modules/mob/living/carbon/human/species_types/vox.dm
  code/modules/surgery/organs/tongue.dm
  icons/mob/species/vox/eyes.dmi
  icons/mob/species/vox/head.dmi
  icons/mob/species/vox/helmet.dmi
  icons/mob/species/vox/shoes.dmi
  icons/mob/species/vox/suit.dmi
Labels: Fix

#708 More crew objectives
  code/modules/crew_objectives/civilian_objectives.dm
  code/modules/crew_objectives/command_objectives.dm
  code/modules/crew_objectives/security_objectives.dm
Labels: Feature

#712 More Misc Vox Sprite fixes
  code/modules/hydroponics/beekeeping/beekeeper_suit.dm
  icons/mob/species/vox/head.dmi
  icons/mob/species/vox/suit.dmi
Labels: Tweak

#711 Rev Name Generation TGPort
  code/game/gamemodes/miniantags/revenant/revenant.dm
  strings/revenant_names.json
Labels: Feature, Port

#707 Makes Asteroid with Rockets require emagging the console
  code/datums/shuttles.dm
  code/game/machinery/computer/communications.dm
  config/unbuyableshuttles.txt
Labels: Tweak

#703 Syndie Bag/Mag Update And Fix
  code/game/objects/items/storage/backpack.dm
  code/modules/projectiles/boxes_magazines/external_mag.dm
  icons/obj/ammo.dmi
  icons/obj/guns/projectile.dmi
Labels: Fix, Tweak

#664 Somewhere between Crewsimov and Asimov lawset
  code/datums/ai_laws.dm
Labels: Config Change, Tweak

#723 Remove picking sec officers ahead of crew
  code/controllers/subsystem/job.dm
Labels: Tweak

#725 Fixes broken light tubes producing light
  code/modules/power/lighting.dm
Labels: Fix

#719 Adds defines for organ slots
  code/__DEFINES/DNA.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/diseases/advance/symptoms/deafness.dm
  code/datums/diseases/advance/symptoms/vision.dm
  code/game/gamemodes/changeling/evolution_menu.dm
  code/game/gamemodes/changeling/powers/augmented_eyesight.dm
  code/game/gamemodes/changeling/powers/regenerate.dm
  code/game/machinery/cloning.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/tanks/tanks.dm
  code/modules/clothing/neck/neck.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/carbon_movement.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/ipc.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/say.dm
  code/modules/mob/living/carbon/status_procs.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/taste.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/station_goals/dna_vault.dm
  code/modules/surgery/eye_surgery.dm
  code/modules/surgery/organ_manipulation.dm
  code/modules/surgery/organs/appendix.dm
  code/modules/surgery/organs/augments_arms.dm
  code/modules/surgery/organs/augments_chest.dm
  code/modules/surgery/organs/augments_eyes.dm
  code/modules/surgery/organs/augments_internal.dm
  code/modules/surgery/organs/ears.dm
  code/modules/surgery/organs/eyes.dm
  code/modules/surgery/organs/heart.dm
  code/modules/surgery/organs/liver.dm
  code/modules/surgery/organs/lungs.dm
  code/modules/surgery/organs/organ_internal.dm
  code/modules/surgery/organs/stomach.dm
  code/modules/surgery/organs/tails.dm
  code/modules/surgery/organs/tongue.dm
  code/modules/surgery/organs/vocal_cords.dm
  code/modules/zombie/items.dm
  code/modules/zombie/organs.dm
Labels: Backend

#713 Slime People and Pod People buffs.
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
Labels: Feature, Tweak

#700 Fixes prefs breaking after reentering the game
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
Labels: Fix

#704 Vox examine message tweak
  code/modules/mob/living/carbon/human/species_types/vox.dm
Labels: Tweak

#701 Antag Playtime Requirements
  code/controllers/configuration/entries/game_options.dm
  code/game/gamemodes/game_mode.dm
  config/game_options.txt
Labels: Config Change, Feature

#670 Return of the Plasmamen
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  config/game_options.txt
Labels: Config Change, Tweak

#728 New Disease that turns people into tiny lizards
  code/datums/diseases/transformation.dm
Labels: Feature

#733 The long anticipated creampie refactor
  code/modules/food_and_drinks/food/snacks_pie.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/ethari.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/vox.dm
  icons/effects/creampie.dmi
Labels: Fix

#694 Refactors Robotic Emotes
  code/datums/emotes.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/silicon/robot/emote.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Refactor/Code Improvement, Tweak

#705 Tweaks to brain damage messages
  strings/brain_damage_lines.json
Labels: Tweak

#727 Armblade sting gives admin logging
  code/game/gamemodes/changeling/powers/tiny_prick.dm
Labels: Admin Tools

#738 Logging login and logout times
  code/modules/mob/living/login.dm
  code/modules/mob/living/logout.dm
Labels: Admin Tools

#714 Messenger Bags
  code/_globalvars/lists/flavor_misc.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/structures/crates_lockers/closets/secure/personal.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/jobs/job_types/blueshield.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/engineering.dm
  code/modules/jobs/job_types/job.dm
  code/modules/jobs/job_types/medical.dm
  code/modules/jobs/job_types/science.dm
  code/modules/jobs/job_types/security.dm
  icons/mob/back.dmi
  icons/mob/inhands/equipment/backpack_lefthand.dmi
  icons/mob/inhands/equipment/backpack_righthand.dmi
  icons/obj/storage.dmi
Labels: Feature, Port

#739 New latejoin selection screen
  code/modules/jobs/jobs.dm
  code/modules/mob/dead/new_player/new_player.dm
Labels: Feature

#734 Fixes a space suit name for vox
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/under/jobs/civilian.dm
  icons/mob/species/vox/suit.dmi
Labels: Fix

#729 Corporate Agent adjustments for admeme purposes
  code/modules/mob/living/carbon/human/species_types/corporate.dm
  icons/mob/human_parts.dmi
Labels: Fix, Tweak

#692 Removes Ling team objectives
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/objective.dm
Labels: Removal, Tweak

#745 Tweaked MetaStation genpop.
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: MetaStation, Tweak

#726 Events tweaking
  code/modules/events/_event.dm
  code/modules/events/anomaly.dm
  code/modules/events/anomaly_bluespace.dm
  code/modules/events/anomaly_flux.dm
  code/modules/events/anomaly_pyro.dm
  code/modules/events/anomaly_vortex.dm
  code/modules/events/electrical_storm.dm
  code/modules/events/portal_storm.dm
  code/modules/events/prison_break.dm
Labels: Tweak

#746 New Silicon scream that is different from IPCs
  code/modules/mob/living/emote.dm
  sound/effects/mob_effects/silicon_scream.ogg
Labels: Feature, Sounds

#755 Space Hotel Staff and Security spawn with their ID Cards now
  _maps/RandomRuins/SpaceRuins/spacehotel.dmm
  code/game/objects/structures/ghost_role_spawners.dm
Labels: Tweak

#758 Add Runic golems to the Magic Mirror blacklist
  code/game/objects/structures/mirror.dm
Labels: Tweak

#753 Event rebalance (aka statistics is hard)
  code/modules/events/brand_intelligence.dm
  code/modules/events/camerafailure.dm
  code/modules/events/carp_migration.dm
  code/modules/events/disease_outbreak.dm
  code/modules/events/dust.dm
  code/modules/events/electrical_storm.dm
  code/modules/events/false_alarm.dm
  code/modules/events/ion_storm.dm
  code/modules/events/mass_hallucination.dm
  code/modules/events/meateor_wave.dm
  code/modules/events/meteor_wave.dm
  code/modules/events/prison_break.dm
  code/modules/events/spider_infestation.dm
  code/modules/events/wormholes.dm
Labels: Balance

#769 Changes delay round end perms from R_SERVER to R_ADMIN
  code/modules/admin/topic.dm
Labels: Admin Tools

#751 Some fixes or sth
  code/modules/crafting/recipes.dm
  code/modules/hydroponics/biogenerator.dm
Labels: Fix

#732 Changeling Eye Fix
  code/game/gamemodes/changeling/powers/augmented_eyesight.dm
Labels: Fix, Port

#775 Moves some admin verbs to the R_ADMIN permission.
  code/modules/admin/admin_verbs.dm
Labels: Admin Tools

#764 Imaginary Friend Tg port
  code/datums/brain_damage/imaginary_friend.dm
Labels: Fix, Port

#765 Monkey AI More CPU Friendly
  code/__DEFINES/monkeys.dm
  code/modules/mob/living/carbon/monkey/combat.dm
  code/modules/mob/living/carbon/monkey/life.dm
Labels: Feature, Port, Tweak

#766 Ammo Cleanup TG Port
  _maps/RandomRuins/SpaceRuins/caravanambush.dmm
  code/game/gamemodes/gang/gang_datum.dm
  code/game/gamemodes/gang/gang_items.dm
  code/game/machinery/porta_turret/portable_turret.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/objects/items/storage/briefcase.dm
  code/game/objects/structures/manned_turret.dm
  code/modules/crafting/recipes.dm
  code/modules/mob/living/simple_animal/hostile/stickman.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/projectiles/ammunition/ammo_casings.dm
  code/modules/projectiles/ammunition/special.dm
  code/modules/projectiles/boxes_magazines/external_mag.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/spells/spell_types/mime.dm
  code/modules/uplink/uplink_item.dm
Labels: Port, Refactor/Code Improvement

#771 removes other collateral damage line from sleeper agents
  code/datums/antagonists/datum_sleeper_agent.dm
Labels: Tweak

#770 buffs sarin stun
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
Labels: Tweak

#779 dead monkey fix
  code/modules/mob/living/carbon/monkey/combat.dm
Labels: Fix

#767 Credits Rework (But not the money kind)
  code/_onclick/hud/credits.dm
  code/game/gamemodes/blob/blob.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/clock_cult/clock_cult.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/devil/devil_game_mode.dm
  code/game/gamemodes/extended/extended.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/gang/gang.dm
  code/game/gamemodes/meteor/meteor.dm
  code/game/gamemodes/miniantags/abduction/abduction.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/gamemodes/wizard/wizard.dm
  code/modules/admin/player_panel.dm
  code/modules/crew_objectives/command_objectives.dm
  icons/title_cards.dmi
Labels: Feature

#781 Credits Tweak
  code/_onclick/hud/credits.dm
Labels: Tweak

#786 Updated Mentor PM's to display correctly
  code/modules/mentor/verbs/mentorpm.dm
Labels: Admin Tools, Fix

#783 Almost Like I Didn't Test This Shit
  code/_onclick/hud/credits.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/clock_cult/clock_cult.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/devil/devil_game_mode.dm
  code/game/gamemodes/gang/gang.dm
  code/game/gamemodes/nuclear/nuclear.dm
  code/game/gamemodes/revolution/revolution.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/gamemodes/wizard/wizard.dm
Labels: Fix

#774 Puts a link to the wiki related to the job upon joining/spawning in
  code/controllers/subsystem/job.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/cargo_service.dm
  code/modules/jobs/job_types/civilian.dm
  code/modules/jobs/job_types/engineering.dm
  code/modules/jobs/job_types/job.dm
  code/modules/jobs/job_types/medical.dm
  code/modules/jobs/job_types/science.dm
  code/modules/jobs/job_types/security.dm
Labels: Feature
